import { Acquisition } from "./Acquisition";
import { ArtObject } from "./ArtObject";
import { Classification } from "./Classification";
import { Color } from "./Color";
import { ColorNormalization } from "./ColorNormalization";
import { Culture } from "./Culture";
import { Dating } from "./Dating";
import { Dimension } from "./Dimension";
import { Label } from "./Label";
import { PrincipalMaker } from "./PrincipalMaker";

export interface ArtObjectDetails extends Omit<ArtObject, 'permitDownload'| 'headerImage'> {
  priref: string;
  language: Culture;
  copyrightHolder?: string;
  colors: Color[];
  colorsWithNormalization: ColorNormalization[];
  normalizedColors: Color[];
  normalized32Colors: Color[];
  materialsThesaurus: string[];
  techniquesThesaurus: string[];
  productionPlacesThesaurus: string[];
  titles: string[];
  description: string;
  labelText?: string;
  objectTypes: string[];
  objectCollection: string[];
  makers: string[];
    principalMakers:           PrincipalMaker[];
    plaqueDescriptionDutch:    string;
    plaqueDescriptionEnglish:  string;
    principalMaker:            string;
    artistRole?:                string;
    associations:              string[];
    acquisition:               Acquisition;
    exhibitions:               string[];
    materials:                 string[];
    techniques:                string[];
    dating:                    Dating;
    classification:            Classification;
    historicalPersons:         string[];
    inscriptions:              string[];
    documentation:             string[];
    catRefRPK:                 string[];
    dimensions:                Dimension[];
    physicalProperties:        string[];
    physicalMedium:            string;
    subTitle:                  string;
    scLabelLine:               string;
    label:                     Label;
    location:                  string;
}
